#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "pyyaml>=6.0",
# ]
# ///
"""Generate coordinates.yaml from apache/security-site's project-coordinates.json.

The triage-assess SKILL needs, per PMC: whether it is a *specialized* team
(has its own security contact, so the Security team only tracks its reports
and does not forward/draft) and the project's threat-model / security-model
link (used to assess a report's scope). project-coordinates.json carries both
(`contact` and `link`), but it lives in a separate checkout that may be absent
or stale on a triager's machine, so we distil it into a committed
coordinates.yaml and refresh that by re-running this script.

specialized == contact is set and is not security@apache.org. A `None` contact
or security@apache.org both mean central triage (ours).

Usage:
    ./build_coordinates.py                 # default source + out
    ./build_coordinates.py --source PATH --out PATH
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import yaml

DEFAULT_SOURCE = Path(
    os.path.expanduser("~/workspace/security/site/scripts/project-coordinates.json")
)
DEFAULT_OUT = Path(__file__).resolve().parent / "coordinates.yaml"

HEADER = (
    "# Generated by build_coordinates.py from apache/security-site\n"
    "# project-coordinates.json. Do not edit by hand; re-run the generator.\n"
    "#\n"
    "# specialized: true  -> the PMC has its own security contact; the Security\n"
    "#   team only TRACKS its reports and does not forward or draft.\n"
    "# specialized: false -> central triage (contact security@apache.org or none).\n"
    "# threat_model: the project's security-model / advisories link, or null.\n"
)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    if not args.source.exists():
        raise SystemExit(
            f"project-coordinates.json not found at {args.source}. Pass --source "
            "(it lives in the apache/security-site checkout, scripts/)."
        )
    data = json.loads(args.source.read_text())

    result = {}
    for slug in sorted(data):
        v = data[slug] or {}
        contact = (v.get("contact") or "").strip() or None
        specialized = bool(contact and contact.lower() != "security@apache.org")
        result[slug] = {
            "name": v.get("name") or slug,
            "contact": contact,
            "specialized": specialized,
            "threat_model": v.get("link") or None,
        }

    with args.out.open("w", encoding="utf-8") as fh:
        fh.write(HEADER)
        yaml.safe_dump(result, fh, sort_keys=True, allow_unicode=True, width=100)

    spec = sum(1 for v in result.values() if v["specialized"])
    print(
        f"Wrote {args.out} — {len(result)} projects, {spec} specialized "
        f"(track-only), {len(result) - spec} central triage."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
