# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Set a repo's per-scan tracking cells in the 'Scan Queue' tab.

The Scan Queue tab is auto-generated by ``build-status-tab``, but its
per-scan tracking block (Scan 1..N, each ``When scanned`` · ``Model send
thread (ponymail)`` · ``When report sent`` · ``Commit hash``) has no
automated source — those cells are **carried over** across rebuilds keyed
by ``(Repo, Branch/tag)``. This command writes them directly for one repo;
the values then survive subsequent refreshes via that carry-over.

Used by ``frontier-model-preparation-forward`` to record a scan's delivery
(``When report sent`` + the tooling-list ponymail permalink) alongside the
scanned commit and date.
"""

from __future__ import annotations

import argparse
import sys

from sheets_writer import SCAN_QUEUE_SHEET
from sheets_writer.columns import col_letter
from sheets_writer.sheets_api import fetch_sheet_grid, get_service
from sheets_writer.status import (
    FIXED_COLS,
    N_SCANS,
    SCAN_BLOCK,
    SCAN_FIELDS,
    SCAN_QUEUE_FIXED,
    SCAN_QUEUE_HEADER,
)

BRANCH_COL = SCAN_QUEUE_FIXED.index("Branch/tag")


def scan_field_col(scan_n: int, field: str) -> int:
    """Pure: 0-based column index of ``field`` within the ``Scan scan_n`` block.

    ``scan_n`` is 1-based (1..N_SCANS); ``field`` is one of ``SCAN_FIELDS``.
    Raises ``ValueError`` on an out-of-range scan number or unknown field.
    """
    if not 1 <= scan_n <= N_SCANS:
        raise ValueError(f"scan number must be 1..{N_SCANS}, got {scan_n}")
    if field not in SCAN_FIELDS:
        raise ValueError(f"unknown scan field {field!r}; expected one of {SCAN_FIELDS}")
    return FIXED_COLS + (scan_n - 1) * SCAN_BLOCK + SCAN_FIELDS.index(field)


def find_scan_queue_row(grid: list[list[str]], repo: str, branch: str = "") -> int | None:
    """Pure: 0-based grid row index of the ``(repo, branch)`` data row, or None.

    Locates the header via ``SCAN_QUEUE_HEADER`` (the tab has title/summary
    rows above it), then scans below it for a row whose ``Repo`` (col 0) and
    ``Branch/tag`` cells match.
    """
    width = len(SCAN_QUEUE_HEADER)
    header_at = -1
    for i, row in enumerate(grid):
        if [c.strip() for c in row[:width]] == SCAN_QUEUE_HEADER:
            header_at = i
            break
    if header_at < 0:
        return None
    for i in range(header_at + 1, len(grid)):
        row = grid[i]
        r_repo = row[0].strip() if row else ""
        r_branch = row[BRANCH_COL].strip() if BRANCH_COL < len(row) else ""
        if r_repo == repo and r_branch == branch:
            return i
    return None


def cmd_scan_queue_set(args: argparse.Namespace) -> int:
    service = get_service()
    grid = fetch_sheet_grid(service, args.spreadsheet_id, SCAN_QUEUE_SHEET)
    row_idx = find_scan_queue_row(grid, args.repo, args.branch or "")
    if row_idx is None:
        print(
            f"No Scan Queue row for repo={args.repo!r} branch={args.branch or ''!r}. "
            "Run build-status-tab first (the repo must be in some PMC's "
            "'Repositories submitted').",
            file=sys.stderr,
        )
        return 2

    fields = {
        "When scanned": args.when_scanned,
        "Model send thread (ponymail)": args.model_thread,
        "When report sent": args.when_report_sent,
        "Commit hash": args.commit,
    }
    row = grid[row_idx]
    data: list[dict] = []
    diffs: list[str] = []
    for field, value in fields.items():
        if value is None:
            continue
        c = scan_field_col(args.scan, field)
        current = row[c] if c < len(row) else ""
        a1 = f"'{SCAN_QUEUE_SHEET}'!{col_letter(c)}{row_idx + 1}"
        diffs.append(f"  Scan {args.scan} · {field}: {current!r} -> {value!r}   [{a1}]")
        data.append({"range": a1, "values": [[value]]})

    if not data:
        print("Nothing to set (no field values provided).")
        return 0

    print(f"Scan Queue row {row_idx + 1} · {args.repo} (branch {args.branch or '<default>'}):")
    for line in diffs:
        print(line)

    if args.dry_run:
        print(f"\nDry run — no changes written. ({len(data)} cells would change.)")
        return 0

    resp = (
        service.spreadsheets()
        .values()
        .batchUpdate(
            spreadsheetId=args.spreadsheet_id,
            body={"valueInputOption": "USER_ENTERED", "data": data},
        )
        .execute()
    )
    print(f"\nApplied. totalUpdatedCells={resp.get('totalUpdatedCells')}")
    return 0
