# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Build the Status / Program totals / Completed / Timeline tabs from the PMCs sheet."""

from __future__ import annotations

import argparse
import datetime
import sys

from sheets_writer import (
    COMPLETED_SHEET,
    IN_PROGRESS_SHEET,
    NOMINATED_COLOR,
    PIPELINE_STATES,
    PROGRAM_TOTALS_SHEET,
    STATE_COLOR,
    STATUS_SHEET,
    TIMELINE_SHEET,
)
from sheets_writer.columns import col_letter
from sheets_writer.prs import parse_pr_urls, query_pr_states
from sheets_writer.sheets_api import fetch_sheet_grid, get_service

# Origin buckets for the threat/security model, in display order, with the
# row label each renders as in the PROGRAM TOTALS "Threat / security models"
# group.
MODEL_ORIGINS = [
    ("existing", "Existing (PMC already had a model)"),
    ("reviewed", "Reviewed & corrected by the Security team"),
    ("security-team", "Generated by the Security team (threat-model-producer)"),
    ("pmc-scovetta", "Prepared by the PMC (Michael Scovetta rubric)"),
    ("none", "No model yet"),
]


def classify_model_origin(model: str, notes: str) -> str:
    """Bucket a PMC's threat/security model by who produced it.

    Heuristic over the free-text ``Security Model`` cell (and ``Notes`` as a
    tie-breaker), returning one of the keys in ``MODEL_ORIGINS``:

    - ``security-team`` — we drafted it (path 3, via threat-model-producer).
    - ``pmc-scovetta``  — the PMC wrote a fresh model using the Scovetta rubric
      (path 2 / "path b").
    - ``reviewed``      — the PMC had an existing model that we reviewed and
      corrected/augmented (a discoverability or section-additions PR we opened).
    - ``existing``      — the PMC had an existing model we accepted as-is.
    - ``none``          — no model recorded yet.

    Pure function. Buckets are derived from cell text, so a wrongly tagged cell
    is bucketed wrongly — operators fix it by correcting the ``Security Model`` cell.
    """
    if not model.strip():
        return "none"
    text = f"{model}\n{notes}".lower()
    if (
        "path 3" in text
        or "we drafted" in text
        or "we draft" in text
        or "threat-model-producer" in text
    ):
        return "security-team"
    if (
        "path 2" in text
        or "path b" in text
        or "pmc is writing" in text
        or "pmc writes" in text
        or "pmc wrote" in text
        or "per the apache security threat-model rubric" in text
        or ("scovetta" in text and ("pmc" in text or "rubric" in text))
    ):
        return "pmc-scovetta"
    # Path 1 (existing): "reviewed" if we opened a correction/discoverability PR,
    # else accepted as-is. Bare "discoverability re-confirmed" is NOT a correction.
    corrected_markers = (
        "potiuk fork",
        "by jarek",
        "discoverability pr",
        "additions",
        "polish",
        "deepening",
        "we added",
        "path-2 pr",
        "routing agents.md",
        "agents.md → security.md",
        "agents.md -> security.md",
    )
    return "reviewed" if any(m in text for m in corrected_markers) else "existing"


def compute_pmc_status(row: list[str], col_idx: dict[str, int]) -> dict:
    """Derive the pipeline state of a single PMC row.

    Calls ``query_pr_states`` per URL, which shells out to ``gh``. Pure
    logic for the state machine itself; the network side-effect is the
    PR-state lookup.
    """

    def cell(name: str) -> str:
        idx = col_idx.get(name)
        if idx is None or idx >= len(row):
            return ""
        return (row[idx] or "").strip()

    pmc = cell("PMC Name")
    slug = cell("PMC Slug")
    requested_date = cell("Request date")
    repos_requested = cell("Repositories requested")
    repos_submitted = cell("Repositories submitted")
    contact = cell("Contact Person")
    backup = cell("Backup contact")
    model = cell("Security Model")
    model_verified = cell("Security model verified")
    submitted_date = cell("Date scan requested")
    received_date = cell("Date scan received")
    forwarded_date = cell("Forwarded scan to PMC")
    pr_issues = cell("PR/Issues")
    notes = cell("Notes")

    # State machine.
    if forwarded_date:
        state = "Delivered"
    elif received_date:
        state = "Triaging"
    elif submitted_date:
        state = "Submitted"
    elif model_verified:
        state = "Ready"
    else:
        state = "Pre-flight"

    if model_verified:
        model_status = "Verified"
    elif model:
        model_status = "Nominated"
    else:
        model_status = "Missing"

    repo_count = len(
        [r for r in repos_requested.splitlines() if r.strip() and not r.strip().startswith("#")]
    )
    submitted_count = len(
        [r for r in repos_submitted.splitlines() if r.strip() and not r.strip().startswith("#")]
    )

    pr_urls = parse_pr_urls(pr_issues)
    pr_state = (
        query_pr_states(pr_urls) if pr_urls else {"open": 0, "merged": 0, "closed": 0, "errors": []}
    )

    return {
        "pmc": pmc,
        "slug": slug,
        "state": state,
        "model_status": model_status,
        "repos_requested_count": repo_count,
        "repos_submitted_count": submitted_count,
        "repos_requested": repos_requested,
        "repos_submitted": repos_submitted,
        "request_date": requested_date,
        "model_verified_date": model_verified,
        "submitted_date": submitted_date,
        "received_date": received_date,
        "forwarded_date": forwarded_date,
        "contact": contact,
        "backup": backup,
        "model": model,
        "pr_issues": pr_issues,
        "pr_urls": pr_urls,
        "pr_open": pr_state["open"],
        "pr_merged": pr_state["merged"],
        "pr_closed": pr_state["closed"],
        "pr_errors": pr_state["errors"],
        "notes": notes,
        "model_origin": classify_model_origin(model, notes),
    }


class _Tab:
    """Accumulator for one sheet's values + per-row colors + header rows."""

    def __init__(self) -> None:
        self.values: list[list] = []
        self.colors: list[tuple[int, dict, int]] = []
        self.headers: list[int] = []

    def row(self, cells: list, *, color: dict | None = None, span: int = 11, header: bool = False):
        i = len(self.values)
        self.values.append(cells)
        if color is not None:
            self.colors.append((i, color, span))
        if header:
            self.headers.append(i)


def _ensure_sheet(service, spreadsheet_id, title, by_title, rename_from=None) -> int:
    """Return the sheetId for ``title``, creating it (or renaming ``rename_from``
    into it, to migrate the old single tab) if absent. ``by_title`` maps title →
    sheetId and is updated in place."""
    if title in by_title:
        return by_title[title]
    if rename_from and rename_from in by_title:
        sid = by_title[rename_from]
        service.spreadsheets().batchUpdate(
            spreadsheetId=spreadsheet_id,
            body={
                "requests": [
                    {
                        "updateSheetProperties": {
                            "properties": {"sheetId": sid, "title": title},
                            "fields": "title",
                        }
                    }
                ]
            },
        ).execute()
        del by_title[rename_from]
        by_title[title] = sid
        return sid
    resp = (
        service.spreadsheets()
        .batchUpdate(
            spreadsheetId=spreadsheet_id,
            body={
                "requests": [
                    {
                        "addSheet": {
                            "properties": {
                                "title": title,
                            }
                        }
                    }
                ]
            },
        )
        .execute()
    )
    sid = resp["replies"][0]["addSheet"]["properties"]["sheetId"]
    by_title[title] = sid
    return sid


def _write_tab(service, spreadsheet_id, title, sheet_id, tab: _Tab, wrap_col=None) -> None:
    """Clear ``title``, write the tab's values, and apply formatting (bold
    headers, row background colors, optional text-wrap on one column)."""
    service.spreadsheets().values().clear(
        spreadsheetId=spreadsheet_id, range=f"'{title}'"
    ).execute()
    ncols = max((len(r) for r in tab.values), default=1)
    end_col = col_letter(ncols - 1)
    service.spreadsheets().values().update(
        spreadsheetId=spreadsheet_id,
        range=f"'{title}'!A1:{end_col}{max(len(tab.values), 1)}",
        valueInputOption="RAW",
        body={"values": tab.values},
    ).execute()

    # Clear formatting first, then re-apply (bold → colors → wrap). Also unfreeze
    # the sheet so there is no fixed no-scroll header block (older tabs were
    # created with a frozen first row; this clears it on every refresh).
    requests: list[dict] = [
        {
            "repeatCell": {
                "range": {"sheetId": sheet_id},
                "cell": {"userEnteredFormat": {}},
                "fields": "userEnteredFormat",
            }
        },
        {
            "updateSheetProperties": {
                "properties": {
                    "sheetId": sheet_id,
                    "gridProperties": {"frozenRowCount": 0, "frozenColumnCount": 0},
                },
                "fields": "gridProperties.frozenRowCount,gridProperties.frozenColumnCount",
            }
        },
    ]
    for r in sorted(set(tab.headers)):
        requests.append(
            {
                "repeatCell": {
                    "range": {
                        "sheetId": sheet_id,
                        "startRowIndex": r,
                        "endRowIndex": r + 1,
                        "startColumnIndex": 0,
                        "endColumnIndex": ncols,
                    },
                    "cell": {"userEnteredFormat": {"textFormat": {"bold": True}}},
                    "fields": "userEnteredFormat.textFormat.bold",
                }
            }
        )
    for r, color, span in tab.colors:
        requests.append(
            {
                "repeatCell": {
                    "range": {
                        "sheetId": sheet_id,
                        "startRowIndex": r,
                        "endRowIndex": r + 1,
                        "startColumnIndex": 0,
                        "endColumnIndex": span,
                    },
                    "cell": {"userEnteredFormat": {"backgroundColor": color}},
                    "fields": "userEnteredFormat.backgroundColor",
                }
            }
        )
    if wrap_col is not None:
        requests.append(
            {
                "repeatCell": {
                    "range": {
                        "sheetId": sheet_id,
                        "startColumnIndex": wrap_col,
                        "endColumnIndex": wrap_col + 1,
                    },
                    "cell": {"userEnteredFormat": {"wrapStrategy": "WRAP"}},
                    "fields": "userEnteredFormat.wrapStrategy",
                }
            }
        )
    service.spreadsheets().batchUpdate(
        spreadsheetId=spreadsheet_id, body={"requests": requests}
    ).execute()


def cmd_build_status_tab(args: argparse.Namespace) -> None:
    service = get_service()
    today = datetime.date.today().isoformat()

    # 1. Read source data.
    grid = fetch_sheet_grid(service, args.spreadsheet_id, "PMCs")
    if not grid or len(grid) < 2:
        sys.exit("PMCs sheet has no data rows.")
    header = grid[0]
    col_idx = {h: i for i, h in enumerate(header)}

    entries = []
    for row in grid[1:]:
        scan_requested_idx = col_idx.get("Scan Requested", -1)
        scan_requested = (
            row[scan_requested_idx].strip() if 0 <= scan_requested_idx < len(row) else ""
        )
        if scan_requested != "Yes":
            continue
        entries.append(compute_pmc_status(row, col_idx))

    state_order = {s: i for i, s in enumerate(PIPELINE_STATES)}
    in_flight = sorted(
        [e for e in entries if e["state"] != "Delivered"],
        key=lambda e: (-state_order.get(e["state"], 0), e["request_date"]),
    )
    completed = sorted(
        [e for e in entries if e["state"] == "Delivered"],
        key=lambda e: e["forwarded_date"],
    )

    # 2. Program-wide totals.
    total_pmcs = len(entries)
    total_open = sum(e["pr_open"] for e in entries)
    total_merged = sum(e["pr_merged"] for e in entries)
    total_closed = sum(e["pr_closed"] for e in entries)
    total_prs = total_open + total_merged + total_closed
    pmcs_with_prs = len(
        [e for e in entries if (e["pr_open"] + e["pr_merged"] + e["pr_closed"]) > 0]
    )
    state_counts = {s: sum(1 for e in entries if e["state"] == s) for s in PIPELINE_STATES}
    pmcs_sent_to_vendor = sum(
        state_counts.get(s, 0) for s in ("Submitted", "Triaging", "Delivered")
    )
    pmcs_results_back = sum(state_counts.get(s, 0) for s in ("Triaging", "Delivered"))
    total_repos_requested = sum(e["repos_requested_count"] for e in entries)
    total_repos_submitted = sum(e["repos_submitted_count"] for e in entries)
    origin_counts = {
        key: sum(1 for e in entries if e["model_origin"] == key) for key, _ in MODEL_ORIGINS
    }
    # Per-origin model progress: "In progress" = model nominated but not yet
    # verified; "Complete" = model verified. (The "none" bucket has no model, so
    # neither applies.)
    origin_in_progress = {
        key: sum(
            1 for e in entries if e["model_origin"] == key and e["model_status"] == "Nominated"
        )
        for key, _ in MODEL_ORIGINS
    }
    origin_complete = {
        key: sum(1 for e in entries if e["model_origin"] == key and e["model_status"] == "Verified")
        for key, _ in MODEL_ORIGINS
    }

    # 3. Build the "Status in progress" tab: legend, grouped totals, in-flight.
    ip = _Tab()
    ip.row([f"Glasswing scan pipeline — Status in progress · as of {today}"], header=True)
    ip.row(
        [
            "Source: PMCs sheet · regenerated by sheets-writer build-status-tab. "
            "Program totals are on the 'Program totals' tab; completed PMCs on "
            "'Completed'; date milestones on 'Timeline'."
        ]
    )
    ip.row([""])
    # Legend: one colour swatch cell (column A) + its description (column B), so
    # only a single cell is coloured per entry rather than the whole row.
    ip.row(["LEGEND", "swatch colour = pipeline state"], header=True)
    ip.row(["", "Pre-flight — model not yet verified"], color=STATE_COLOR["Pre-flight"], span=1)
    ip.row(
        ["", "Pre-flight — model nominated, pending verification"], color=NOMINATED_COLOR, span=1
    )
    ip.row(
        ["", "Ready — model verified, awaiting operator submit"], color=STATE_COLOR["Ready"], span=1
    )
    ip.row(
        ["", "Submitted — sent to vendor, awaiting results"], color=STATE_COLOR["Submitted"], span=1
    )
    ip.row(
        ["", "Triaging — results back, pre-forward sanity check"],
        color=STATE_COLOR["Triaging"],
        span=1,
    )
    ip.row(
        ["", "Delivered — forwarded to PMC (see 'Completed' tab)"],
        color=STATE_COLOR["Delivered"],
        span=1,
    )
    ip.row([""])

    ip.row(["IN FLIGHT"], header=True)
    ip.row(
        [
            "PMC",
            "Slug",
            "Status",
            "Repos requested",
            "Model",
            "PRs open",
            "PRs merged",
            "PRs total",
            "Request date",
            "Model verified",
            "Notes / PR / Issues",
        ],
        header=True,
    )
    if not in_flight:
        ip.row(["(none in flight)"])
    for e in in_flight:
        pr_total = e["pr_open"] + e["pr_merged"] + e["pr_closed"]
        has = bool(e["pr_urls"])
        # Nominated-but-unverified models sit between Pre-flight red and Ready
        # yellow, so they get the orange shade instead of the flat Pre-flight red.
        color = NOMINATED_COLOR if e["model_status"] == "Nominated" else STATE_COLOR[e["state"]]
        ip.row(
            [
                e["pmc"],
                e["slug"],
                e["state"],
                e["repos_requested_count"],
                e["model_status"],
                e["pr_open"] if has else "—",
                e["pr_merged"] if has else "—",
                pr_total if has else "—",
                e["request_date"],
                e["model_verified_date"] or "—",
                (e["pr_issues"] or "") + (("  ·  " + e["notes"]) if e["notes"] else ""),
            ],
            color=color,
        )

    # 4. Build the "Program totals" tab (the grouped rollup, on its own tab now).
    pt = _Tab()
    pt.row([f"Glasswing scan pipeline — Program totals · as of {today}"], header=True)
    pt.row(["Pipeline"], header=True)
    pt.row(["  PMCs opted in (Scan Requested = Yes)", total_pmcs])
    pt.row(["  Pre-flight (model not yet verified)", state_counts["Pre-flight"]])
    pt.row(["  Ready (model verified, awaiting operator submit)", state_counts["Ready"]])
    pt.row(["  Submitted (sent to vendor, awaiting results)", state_counts["Submitted"]])
    pt.row(["  Triaging (results back, pre-forward sanity check)", state_counts["Triaging"]])
    pt.row(["  Delivered (forwarded to PMC)", state_counts["Delivered"]])
    pt.row(["  Sent to vendor (Submitted+Triaging+Delivered)", pmcs_sent_to_vendor])
    pt.row(["  Results back (Triaging+Delivered)", pmcs_results_back])
    pt.row(["Repositories"], header=True)
    pt.row(["  Repos requested across PMCs", total_repos_requested])
    pt.row(["  Repos submitted to vendor", total_repos_submitted])
    pt.row(["Pull requests"], header=True)
    pt.row(["  PMCs with at least one PR opened", pmcs_with_prs])
    pt.row(["  PRs open (not yet merged)", total_open])
    pt.row(["  PRs merged", total_merged])
    pt.row(["  PRs total", total_prs])
    if total_closed:
        pt.row(["  (of which closed without merge)", total_closed])
    pt.row(["Threat / security models", "Total", "In progress", "Complete"], header=True)
    for key, label in MODEL_ORIGINS:
        if key == "none":
            pt.row([f"  {label}", origin_counts[key], "—", "—"])
        else:
            pt.row(
                [f"  {label}", origin_counts[key], origin_in_progress[key], origin_complete[key]]
            )

    # 5. Build the "Completed" tab.
    cp = _Tab()
    cp.row([f"Glasswing scan pipeline — Completed · as of {today}"], header=True)
    cp.row(
        [
            "PMC",
            "Slug",
            "Repos submitted",
            "PRs open",
            "PRs merged",
            "PRs total",
            "Submitted",
            "Received",
            "Forwarded",
            "Days end-to-end",
        ],
        header=True,
    )
    if not completed:
        cp.row(["(none yet)"])
    for e in completed:
        try:
            d1 = datetime.date.fromisoformat(e["request_date"])
            d2 = datetime.date.fromisoformat(e["forwarded_date"])
            e2e: object = (d2 - d1).days
        except Exception:  # noqa: BLE001 — date parsing tolerant
            e2e = ""
        pr_total = e["pr_open"] + e["pr_merged"] + e["pr_closed"]
        has = bool(e["pr_urls"])
        cp.row(
            [
                e["pmc"],
                e["slug"],
                e["repos_submitted_count"],
                e["pr_open"] if has else "—",
                e["pr_merged"] if has else "—",
                pr_total if has else "—",
                e["submitted_date"] or "—",
                e["received_date"] or "—",
                e["forwarded_date"] or "—",
                e2e,
            ],
            color=STATE_COLOR["Delivered"],
            span=10,
        )

    # 6. Build the "Timeline" tab (wide format — chart-ready: X=date cols, Y=PMC).
    tl = _Tab()
    tl.row([f"Glasswing scan pipeline — Timeline · as of {today}"], header=True)
    tl.row(["Wide format — scatter chart: X = a date column, Y = PMC, one series per milestone."])
    tl.row(["PMC", "Requested", "Ready", "Submitted", "Received", "Forwarded"], header=True)
    for e in sorted(entries, key=lambda x: x["request_date"]):
        tl.row(
            [
                e["pmc"],
                e["request_date"] or "",
                e["model_verified_date"] or "",
                e["submitted_date"] or "",
                e["received_date"] or "",
                e["forwarded_date"] or "",
            ]
        )

    if args.dry_run:
        print(
            f"Would write 4 tabs — '{IN_PROGRESS_SHEET}' ({len(ip.values)} rows, "
            f"{len(in_flight)} in flight), '{PROGRAM_TOTALS_SHEET}' ({len(pt.values)} rows), "
            f"'{COMPLETED_SHEET}' ({len(completed)} completed), "
            f"'{TIMELINE_SHEET}' ({len(entries)} events). Model origins: "
            + ", ".join(f"{k}={origin_counts[k]}" for k, _ in MODEL_ORIGINS)
            + "."
        )
        return

    # 7. Ensure the four tabs exist (migrating the old single 'Status' tab into
    #    'Status in progress'), then write each.
    meta = service.spreadsheets().get(spreadsheetId=args.spreadsheet_id).execute()
    by_title = {
        s["properties"]["title"]: s["properties"]["sheetId"] for s in meta.get("sheets", [])
    }
    ip_id = _ensure_sheet(
        service, args.spreadsheet_id, IN_PROGRESS_SHEET, by_title, rename_from=STATUS_SHEET
    )
    pt_id = _ensure_sheet(service, args.spreadsheet_id, PROGRAM_TOTALS_SHEET, by_title)
    cp_id = _ensure_sheet(service, args.spreadsheet_id, COMPLETED_SHEET, by_title)
    tl_id = _ensure_sheet(service, args.spreadsheet_id, TIMELINE_SHEET, by_title)

    _write_tab(service, args.spreadsheet_id, IN_PROGRESS_SHEET, ip_id, ip, wrap_col=10)
    _write_tab(service, args.spreadsheet_id, PROGRAM_TOTALS_SHEET, pt_id, pt)
    _write_tab(service, args.spreadsheet_id, COMPLETED_SHEET, cp_id, cp)
    _write_tab(service, args.spreadsheet_id, TIMELINE_SHEET, tl_id, tl)

    print(
        f"Refreshed: '{IN_PROGRESS_SHEET}' ({len(in_flight)} in flight), "
        f"'{PROGRAM_TOTALS_SHEET}' ({len(pt.values)} rows), "
        f"'{COMPLETED_SHEET}' ({len(completed)} completed), "
        f"'{TIMELINE_SHEET}' ({len(entries)} events). Model origins: "
        + ", ".join(f"{k}={origin_counts[k]}" for k, _ in MODEL_ORIGINS)
        + "."
    )
